using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CountDown
{
    public partial class EditEvent : Form
    {
        bool mouseDown;
        private Point Offset;

        private SqlConnection Con;
        private SqlCommand Command;
        string conString = "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\blert\\OneDrive\\Documents\\db_calendar.mdf;Integrated Security=True;Connect Timeout=30";

        public EditEvent()
        {
            InitializeComponent();
        }

        private void EditEvent_Load(object sender, EventArgs e)
        {
            
            ShowTheData();
        }
        public void ShowTheData()
        {
            if(Event.getEventName != "" || UserControlDays.static_day != "")
            {
                Con = new SqlConnection(conString);
                Con.Open();
                string Query = "SELECT * FROM tbl_calendar where event = @event";
                Command = Con.CreateCommand();
                Command.CommandText = Query;
                Command.Parameters.AddWithValue("@event", Event.getEventName);
                SqlDataReader reader = Command.ExecuteReader();
                frmMDI.instance.eventsHold.Controls.Clear();
                while (reader.Read())
                {
                    string TempEvent = reader["event"].ToString();
                    string TempDate = frmMDI.static_year + "-" + frmMDI.static_month + "-" + UserControlDays.static_day;
                    int TempStartingTime = StartingTime.Items.IndexOf(reader["StartingTime"].ToString());
                    int TempAmOrPmTime = AmOrPm.Items.IndexOf(reader["AmOrPmTime"].ToString());
                    int TempEndingTime = EndingTime.Items.IndexOf(reader["EndingTime"].ToString());
                    eventTxt.Text = TempEvent;
                    dateTxt.Text = TempDate;
                   
                    if(TempStartingTime != -1 && TempAmOrPmTime != -1)
                    {
                        StartingTime.SelectedIndex = TempStartingTime;
                        AmOrPm.SelectedIndex = TempAmOrPmTime;
                        EndingTime.SelectedIndex = 0;
                        UpdateCombobox();
                    }
                }
                reader.Dispose();
                Command.Dispose();
                Con.Close();
                UserControlDays temp = new UserControlDays();
                temp.ShowEvent();
            }
            
        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {
            this.Close();
            Event.getEventName = "";
        }

        public void UpdateCombobox()
        {
            if (StartingTime.SelectedIndex == 0)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("12:15PM");
                    EndingTime.Items.Add("12:30PM");
                    EndingTime.Items.Add("12:45PM");
                    EndingTime.Items.Add("1:10PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("12:15AM");
                    EndingTime.Items.Add("12:30AM");
                    EndingTime.Items.Add("12:45AM");
                    EndingTime.Items.Add("1:10AM");
                    EndingTime.Items.Add("1:30AM");
                    EndingTime.Items.Add("2:00AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 1)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("1:15PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("1:45PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("1:15AM");
                    EndingTime.Items.Add("1:30AM");
                    EndingTime.Items.Add("1:45AM");
                    EndingTime.Items.Add("2:00AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 2)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("2:15PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("2:45PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("2:15AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("2:45AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 3)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("3:15PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("3:45PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("3:15AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("3:45AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 4)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("4:15PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("4:45PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("4:15AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("4:45AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 5)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("5:15PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("5:45PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("5:15AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("5:45AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 6)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("6:15PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("6:45PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("6:15AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("6:45AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 7)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("7:15PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("7:45PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("7:15AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("7:45AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 8)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("8:15PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("8:45PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("8:15AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("8:45AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 9)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("9:15PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("9:45PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("9:15AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("9:45AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 10)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("10:15PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("10:45PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("10:15AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("10:45AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 11)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("11:15PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("11:45PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("11:15AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("11:45AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
        }

        private void StartingTime_SelectedIndexChanged(object sender, EventArgs e)
        {
            EndingTime.SelectedIndex = 0;
            if (StartingTime.SelectedIndex == 0)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("12:15PM");
                    EndingTime.Items.Add("12:30PM");
                    EndingTime.Items.Add("12:45PM");
                    EndingTime.Items.Add("1:10PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("12:15AM");
                    EndingTime.Items.Add("12:30AM");
                    EndingTime.Items.Add("12:45AM");
                    EndingTime.Items.Add("1:10AM");
                    EndingTime.Items.Add("1:30AM");
                    EndingTime.Items.Add("2:00AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 1)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("1:15PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("1:45PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("1:15AM");
                    EndingTime.Items.Add("1:30AM");
                    EndingTime.Items.Add("1:45AM");
                    EndingTime.Items.Add("2:00AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 2)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("2:15PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("2:45PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("2:15AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("2:45AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 3)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("3:15PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("3:45PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("3:15AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("3:45AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 4)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("4:15PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("4:45PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("4:15AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("4:45AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 5)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("5:15PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("5:45PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("5:15AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("5:45AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 6)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("6:15PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("6:45PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("6:15AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("6:45AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 7)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("7:15PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("7:45PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("7:15AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("7:45AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 8)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("8:15PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("8:45PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("8:15AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("8:45AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 9)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("9:15PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("9:45PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("9:15AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("9:45AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 10)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("10:15PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("10:45PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("10:15AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("10:45AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 11)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("11:15PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("11:45PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("11:15AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("11:45AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }

        }

        private void AmOrPm_SelectedIndexChanged(object sender, EventArgs e)
        {
            UpdateCombobox();
            EndingTime.SelectedIndex = 0;
        }

        private void saveBtn_Click(object sender, EventArgs e)
        {
            if(eventTxt.Text != "" || dateTxt.Text != "" || StartingTime.SelectedIndex != -1 || AmOrPm.SelectedIndex != -1 || EndingTime.SelectedIndex != -1 || Event.getEventName != "" || EndingTime.SelectedItem == null)
            {
                DialogResult result = MessageBox.Show("Are you sure you wanna make this changes?", "Confirm", MessageBoxButtons.YesNo);
                if(result == DialogResult.Yes)
                {
                    Con.Open();

                    Command = new SqlCommand("UPDATE tbl_calendar SET event = @event2, date = @date, StartingTime = @value1, AmOrPmTime = @value2, EndingTime = @value3 WHERE event = @event1", Con);

                    if(EndingTime.SelectedItem == null)
                    {
                        EndingTime.SelectedIndex = 0; 
                    }
                    Command.Parameters.AddWithValue("@event1", Event.getEventName);
                    Command.Parameters.AddWithValue("@event2", eventTxt.Text);
                    Command.Parameters.AddWithValue("@date", dateTxt.Text);
                    Command.Parameters.AddWithValue("@value1", StartingTime.SelectedItem.ToString());
                    Command.Parameters.AddWithValue("@value2", AmOrPm.SelectedItem.ToString());
                    Command.Parameters.AddWithValue("@value3", EndingTime.SelectedItem.ToString());
                    MessageBox.Show("Your Event has been updated!");
                    Command.ExecuteNonQuery();
                    UserControlDays temp = new UserControlDays();
                    temp.ShowEvent();
                    Con.Close();
                    Event.getEventName = "";
                    this.Close();
                }
            }
            else
            {
                MessageBox.Show("Missing Data!");
                UserControlDays temp = new UserControlDays();
                temp.ShowEvent();
            }
        }

        private void EditEvent_MouseDown(object sender, MouseEventArgs e)
        {
           
        }

        private void EditEvent_MouseMove(object sender, MouseEventArgs e)
        {
           
        }

        private void TopHeader_MouseDown(object sender, MouseEventArgs e)
        {
            Offset.X = (int)e.X;
            Offset.Y = (int)e.Y;
            mouseDown = true;
        }

        private void TopHeader_MouseMove(object sender, MouseEventArgs e)
        {
            if (mouseDown == true)
            {
                Point CurrentScreen = PointToScreen(e.Location);
                Location = new Point(CurrentScreen.X - Offset.X, CurrentScreen.Y - Offset.Y);
            }
        }

        private void TopHeader_MouseUp(object sender, MouseEventArgs e)
        {
            mouseDown = false;
        }
    }
}
