using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;



namespace CountDown
{
    public partial class EventFrom : Form
    {
        bool mouseDown;
        private Point Offset;

        DataFunctions con;
        public EventFrom()
        {
            InitializeComponent();
            con = new DataFunctions();
        }

        private void EventFrom_Load(object sender, EventArgs e)
        {
            dateTxt.Text = Form1.static_year + "-" + Form1.static_month + "-" + UserControlDays.static_day;
            StartingTime.SelectedIndex = 0;
            AmOrPm.SelectedIndex = 0;
            UpdateCombobox();
            EndingTime.SelectedIndex = -1;
        }
      
        private void saveBtn_Click(object sender, EventArgs e)
        {
            
            try
            {
                if(dateTxt.Text == "" || eventTxt.Text == "" || StartingTime.SelectedIndex == -1 || AmOrPm.SelectedIndex == -1 || EndingTime.SelectedIndex == -1)
                {
                    MessageBox.Show("Missing Data!");
                }
                else
                { 
                    string Events = eventTxt.Text;
                    string dateTime = dateTxt.Text;
                    string Query = "insert into tbl_calendar values('{0}','{1}','{2}','{3}','{4}')";
                    Query = string.Format(Query, Events, dateTime, StartingTime.SelectedItem.ToString(), AmOrPm.SelectedItem.ToString(), EndingTime.SelectedItem.ToString());
                    con.SetData(Query);
                    MessageBox.Show("Event Added!");
                    UserControlDays temp = new UserControlDays();
                    temp.ShowEvent();
                    this.Close();
                }
            }
            catch(Exception message)
            {
                MessageBox.Show(message.ToString());
            }
            
            
        }

        private void pictureBox1_MouseHover(object sender, EventArgs e)
        {
            pictureBox1.BackColor = Color.LightGray;
        }

        private void pictureBox1_MouseLeave(object sender, EventArgs e)
        {
            pictureBox1.BackColor = Color.Transparent;
        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void UserControl_Click(object sender, EventArgs e)
        {

        }

        public void UpdateCombobox()
        {
            if (StartingTime.SelectedIndex == 0)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("12:15PM");
                    EndingTime.Items.Add("12:30PM");
                    EndingTime.Items.Add("12:45PM");
                    EndingTime.Items.Add("1:10PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("12:15AM");
                    EndingTime.Items.Add("12:30AM");
                    EndingTime.Items.Add("12:45AM");
                    EndingTime.Items.Add("1:10AM");
                    EndingTime.Items.Add("1:30AM");
                    EndingTime.Items.Add("2:00AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 1)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("1:15PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("1:45PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("1:15AM");
                    EndingTime.Items.Add("1:30AM");
                    EndingTime.Items.Add("1:45AM");
                    EndingTime.Items.Add("2:00AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 2)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("2:15PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("2:45PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("2:15AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("2:45AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 3)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("3:15PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("3:45PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("3:15AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("3:45AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 4)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("4:15PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("4:45PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("4:15AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("4:45AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 5)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("5:15PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("5:45PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("5:15AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("5:45AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 6)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("6:15PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("6:45PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("6:15AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("6:45AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 7)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("7:15PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("7:45PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("7:15AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("7:45AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 8)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("8:15PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("8:45PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("8:15AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("8:45AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 9)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("9:15PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("9:45PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("9:15AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("9:45AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 10)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("10:15PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("10:45PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("10:15AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("10:45AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 11)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("11:15PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("11:45PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("11:15AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("11:45AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
        }
        private void StartingTime_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (StartingTime.SelectedIndex == 0)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("12:15PM");
                    EndingTime.Items.Add("12:30PM");
                    EndingTime.Items.Add("12:45PM");
                    EndingTime.Items.Add("1:10PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("12:15AM");
                    EndingTime.Items.Add("12:30AM");
                    EndingTime.Items.Add("12:45AM");
                    EndingTime.Items.Add("1:10AM");
                    EndingTime.Items.Add("1:30AM");
                    EndingTime.Items.Add("2:00AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if(StartingTime.SelectedIndex == 1)
            {
                if(AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("1:15PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("1:45PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("1:15AM");
                    EndingTime.Items.Add("1:30AM");
                    EndingTime.Items.Add("1:45AM");
                    EndingTime.Items.Add("2:00AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if(StartingTime.SelectedIndex == 2)
            {
                if(AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("2:15PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("2:45PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("2:15AM");
                    EndingTime.Items.Add("2:30AM");
                    EndingTime.Items.Add("2:45AM");
                    EndingTime.Items.Add("3:00AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if(StartingTime.SelectedIndex == 3)
            {
                if(AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("3:15PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("3:45PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("3:15AM");
                    EndingTime.Items.Add("3:30AM");
                    EndingTime.Items.Add("3:45AM");
                    EndingTime.Items.Add("4:00AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 4)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("4:15PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("4:45PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("4:15AM");
                    EndingTime.Items.Add("4:30AM");
                    EndingTime.Items.Add("4:45AM");
                    EndingTime.Items.Add("5:00AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 5)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("5:15PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("5:45PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("5:15AM");
                    EndingTime.Items.Add("5:30AM");
                    EndingTime.Items.Add("5:45AM");
                    EndingTime.Items.Add("6:00AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 6)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("6:15PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("6:45PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("6:15AM");
                    EndingTime.Items.Add("6:30AM");
                    EndingTime.Items.Add("6:45AM");
                    EndingTime.Items.Add("7:00AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 7)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("7:15PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("7:45PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("7:15AM");
                    EndingTime.Items.Add("7:30AM");
                    EndingTime.Items.Add("7:45AM");
                    EndingTime.Items.Add("8:00AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 8)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("8:15PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("8:45PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("8:15AM");
                    EndingTime.Items.Add("8:30AM");
                    EndingTime.Items.Add("8:45AM");
                    EndingTime.Items.Add("9:00AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 9)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("9:15PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("9:45PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("9:15AM");
                    EndingTime.Items.Add("9:30AM");
                    EndingTime.Items.Add("9:45AM");
                    EndingTime.Items.Add("10:00AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 10)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("10:15PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("10:45PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("10:15AM");
                    EndingTime.Items.Add("10:30AM");
                    EndingTime.Items.Add("10:45AM");
                    EndingTime.Items.Add("11:00AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            else if (StartingTime.SelectedIndex == 11)
            {
                if (AmOrPm.SelectedIndex == 0)
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("11:15PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("11:45PM");
                    EndingTime.Items.Add("12:00AM");
                }
                else
                {
                    EndingTime.Items.Clear();
                    EndingTime.Items.Add("11:15AM");
                    EndingTime.Items.Add("11:30AM");
                    EndingTime.Items.Add("11:45AM");
                    EndingTime.Items.Add("12:00PM");
                    EndingTime.Items.Add("1:00PM");
                    EndingTime.Items.Add("1:30PM");
                    EndingTime.Items.Add("2:00PM");
                    EndingTime.Items.Add("2:30PM");
                    EndingTime.Items.Add("3:00PM");
                    EndingTime.Items.Add("3:30PM");
                    EndingTime.Items.Add("4:00PM");
                    EndingTime.Items.Add("4:30PM");
                    EndingTime.Items.Add("5:00PM");
                    EndingTime.Items.Add("5:30PM");
                    EndingTime.Items.Add("6:00PM");
                    EndingTime.Items.Add("6:30PM");
                    EndingTime.Items.Add("7:00PM");
                    EndingTime.Items.Add("7:30PM");
                    EndingTime.Items.Add("8:00PM");
                    EndingTime.Items.Add("8:30PM");
                    EndingTime.Items.Add("9:00PM");
                    EndingTime.Items.Add("9:30PM");
                    EndingTime.Items.Add("10:00PM");
                    EndingTime.Items.Add("10:30PM");
                    EndingTime.Items.Add("11:00PM");
                    EndingTime.Items.Add("11:30PM");
                    EndingTime.Items.Add("12:00AM");
                }
            }
            
        }

        private void TopHeader_MouseDown(object sender, MouseEventArgs e)
        {
            Offset.X = (int)e.X;
            Offset.Y = (int)e.Y;
            mouseDown = true;
        }

        private void TopHeader_MouseMove(object sender, MouseEventArgs e)
        {
            if (mouseDown == true)
            {
                Point CurrentScreen = PointToScreen(e.Location);
                Location = new Point(CurrentScreen.X - Offset.X, CurrentScreen.Y - Offset.Y);
            }
        }

        private void TopHeader_MouseUp(object sender, MouseEventArgs e)
        {
            mouseDown = false;
        }

        private void AmOrPm_SelectedIndexChanged(object sender, EventArgs e)
        {
            UpdateCombobox();
        }
    }
}
